spring:
  application:
    name: buckpal
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/backpal
    username: root
    password: p@ssw0rd
    hikari:
      minimum-idle: 1
      maximum-pool-size: 10
  flyway:
    enabled: true
    locations: classpath:db/migration
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true